# Post install job running a script to gather the external IP of the LB SVC for stunner
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "stunner.name" .}}-post-install"
  labels: 
    job: "{{- include "stunner.name" .}}-post-install-job"
  namespace: {{ .Values.stunner.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.stunner.postInstall.serviceAccountName }}
      containers:
      - name: post-install
        # image: l7mp/stunner-job:latest
        image: "{{ .Values.stunner.postInstall.image.repository }}{{ .Values.stunner.postInstall.image.name }}:{{ .Values.stunner.postInstall.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.stunner.postInstall.image.pullPolicy}}
        command: ["/bin/bash"]
        args: ["./job.sh"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: post-install-cr
  namespace: {{ .Values.stunner.namespace }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] 
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.stunner.postInstall.serviceAccountName }}
  namespace: {{ .Values.stunner.namespace }}
  labels:
    job: "{{- include "stunner.name" .}}-post-install-job"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    crb: stunner-job
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: post-install-cr
subjects:
- kind: ServiceAccount
  name: {{ .Values.stunner.postInstall.serviceAccountName }}
  namespace: default
---